---
- name: Create hooks folder
  file:
    state: directory
    path: "{{ hooks_folder }}"
    mode: 0755

- name: Create hooks-bin folder
  file:
    state: directory
    path: "{{ hooks_bin_folder }}"
    mode: 0755

- name: Copy pre-receive hook to custom_hooks folder
  copy:
    src: pre-receive
    dest: "{{ hooks_folder }}/pre-receive"
    mode: 0755

- name: Copy secrecy.py to hooks-bin folder
  copy:
    src: secrecy.py
    dest: "{{ hooks_bin_folder }}/secrecy.py"
    mode: 0755

- name: Copy config file secrecy.ini to hooks-bin folder
  template:
    src: secrecy.ini.j2
    dest: "{{ hooks_bin_folder }}/secrecy.ini"
    mode: 0755
  tags:
    - update_config

- name: Uncomment custom_hooks_folder line at gitlab.rb
  lineinfile:
    dest: "{{ gitlab_home }}/config/gitlab.rb"
    state: present
    regexp: '^#\sgitaly\[.custom_hooks_dir.\] = "/var/opt/gitlab/gitaly/custom_hooks"'
    line: "gitaly['custom_hooks_dir'] = \"/var/opt/gitlab/gitaly/custom_hooks\""
  notify: gitlab-ctl reconfigure
