---
- name: Update config and backout if validation fails
  block:
    - name: Update gitlab.rb
      template:
        src: gitlab.rb.j2
        dest: "{{ gitlab_home }}/config/gitlab.rb"
        backup: yes
      register: updated

    - name: Validate gitlab.rb
      community.docker.docker_container_exec:
        container: "{{ gitlab_container_name }}"
        command: "ruby -c /etc/gitlab/gitlab.rb"
      when: "{{ updated.changed }}"
      notify: gitlab-ctl reconfigure

  rescue:
      - name: Restore backup file to original, in the hope the previous configuration was working.
        copy:
          remote_src: true
          dest: "{{ gitlab_home }}/config/gitlab.rb"
          src: "{{ updated.backup_file }}"
        when: "{{ updated.changed }}"

  always:
      - name: We choose to always delete backup, but could copy or move, or only delete in rescue.
        file:
          path: "{{ updated.backup_file }}"
          state: absent
        when: "{{ updated.changed }}"
