---
- name: Ensure data path
  file:
    state: directory
    path: "{{ gitlab_home }}"
    mode: 0755
  register: gitlab_reconfig

- name: Start docker gitlab container
  community.docker.docker_compose_v2:
    state: "{{ 'restarted' if gitlab_reconfig.changed else 'present' }}"
    project_name: gitlab
    definition:
      services:
        gitlab:
          image: "{{ gitlab_docker_image }}"
          container_name: "{{ gitlab_container_name }}"
          ports:
            - "{{ gitlab_http_port }}:80"
            - "{{ gitlab_https_port }}:443"
            - "{{ gitlab_ssh_port }}:22"
            - "{{ gitlab_registry_port }}:5000"
          volumes: "{{ gitlab_volumes }}"
          hostname: "{{ gitlab_host_name }}"
          environment:
            GITLAB_OMNIBUS_CONFIG: "{{ gitlab_omnibus_config }}"
          restart: always

- name: Import backup.yml
  import_tasks: "backup.yml"
  tags:
    - backup

- name: Include extra_files.yml
  include_tasks:
    file: "extra_files.yml"
    apply:
      tags: extra_files
  tags:
    - extra_files
  with_items: "{{ gitlab_extra_files }}"
