---
# tasks file for ageres210784.ansible_gitlab
- name: Ensure data path
  file:
    state: directory
    path: "{{ gitlab_home }}"
    mode: 0755
  register: gitlab_reconfig

- name: Start docker gitlab container
  docker_compose:
    state: present
    project_name: gitlab
    restarted: "{{ 'yes' if gitlab_reconfig.changed else 'no' }}"
    definition:
      version: '2'
      services:
        gitlab:
          image: "{{ gitlab_docker_image }}"
          container_name: "{{ gitlab_container_name }}"
          ports:
            - "{{ gitlab_http_port }}:80"
            - "{{ gitlab_https_port }}:443"
            - "{{ gitlab_ssh_port }}:22"
          volumes:
            - '{{ gitlab_home }}/config:/etc/gitlab'
            - '{{ gitlab_home }}/logs:/var/log/gitlab'
            - '{{ gitlab_home }}/data:/var/opt/gitlab'
          hostname: "{{ gitlab_host_name }}"
          environment:
            GITLAB_OMNIBUS_CONFIG: "{{ gitlab_omnibus_config }}"
          restart: always

- name: Include backup.yml
  include_tasks:
    file: "backup.yml"
    apply:
      tags: backup
  tags:
    - backup
